name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  'Checking':
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: '        Startup ChromeDriver and Display in Ubuntu'
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:99
          # TODO: need to download driver according to electron's version
          wget --directory-prefix=/tmp https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
          unzip -d /tmp/chromedriver /tmp/chromedriver_linux64.zip
          sudo chmod +x /tmp/chromedriver/chromedriver
          /tmp/chromedriver/chromedriver &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: '        Tests'
        shell: bash
        env:
          DISPLAY: ':99'
        run: |
          npm ci
          npm run test:jest
      - name: '        Create COV_REPORT'
        run: |
          mkdir COV_REPORT
      - name: '        Copy jest results'
        run: |
          cp coverage_jest/coverage-final.json COV_REPORT/coverage-final-jest.json
      - name: '     Coverage'
        if: success()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'COV_REPORT-${{ matrix.os }}'
          path: 'COV_REPORT/'
      - name: '      CodeCov'
        if: success()
        uses: codecov/codecov-action@v2.0.1
        with:
          file: 'COV_REPORT*'
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov-${{ matrix.os }}
          fail_ci_if_error: false
